In [228]:
#-------------------------------------
# IMPORT DATASET
#-------------------------------------
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

df = pd.read_csv("/content/Churn_Modelling.csv")
df = pd.DataFrame(df)

In [229]:
#---------------------------------------
# INVESTIGATE DATASET
#---------------------------------------

print(df.info())
df.head()
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB
None
         RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000
mean    76485.889288       1.530200      0.70550        0.515100
std     62397.405202       0.581654      0.45584        0.499797
min         0.000000       1.000000      0.00000        0.000000
25%         0.000000       1.000000      0.00000        0.000000
50%     97198.540000       1.000000      1.00000        1.000000
75%    127644.240000       2.000000      1.00000        1.000000
max    250898.090000       4.000000      1.00000        1.000000

       EstimatedSalary        Exited
count     10000.000000  10000.000000
mean     100090.239881      0.203700
std       57510.492818      0.402769
min          11.580000      0.000000
25%       51002.110000      0.000000
50%      100193.915000      0.000000
75%      149388.247500      0.000000
max      199992.480000      1.000000

In [230]:
#---------------------------------------
# CHECK FOR DUPLICATES
#---------------------------------------
df.duplicated().sum()

np.int64(0)

In [231]:
df['CreditGroup'] = pd.cut(
    df['CreditScore'],
    bins=[0, 580, 670, 740, 851],
    labels=['Poor', 'Fair', 'Good', 'Very Good'],
    right=False
)


df['AgeGroup'] = pd.cut(
    df['Age'],
    bins = [18,30,40,50,60,100],
    labels = ['Young Adult', 'Adult','Middle Age','Late Middle Age','Senior'],
    right = False
)

df['TenureGroup'] = pd.cut(
    df['Tenure'],
    bins = [0,2,5,8,10],
    labels = ['New Customer','Short Term Customer','Established Customer', 'Long Term Customer'],
    right = True
)

df['ProductGroup'] = pd.cut(
    df['NumOfProducts'],
    bins = [0,1,2,3,4],
    labels = ['Single Product Customer', 'Dual Product Customer', 'Triple Product Customer', 'Quadruple Product Customer'],
    right = True
)


df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,CreditGroup,AgeGroup,TenureGroup,ProductGroup
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,Fair,Middle Age,New Customer,Single Product Customer
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,Fair,Middle Age,New Customer,Single Product Customer
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,Poor,Middle Age,Established Customer,Triple Product Customer
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,Good,Adult,New Customer,Dual Product Customer
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,Very Good,Middle Age,New Customer,Single Product Customer

In [232]:
#---------------------------------------
# QUESTION: WHAT IS THE CURRENT CHURN RATE?
#---------------------------------------
tot_customers = df.shape[0]

churned = df[df['Exited'] == 1]
total_churned = churned.shape[0]

churn_pct = round((total_churned / tot_customers)*100,2)
churn_pct #20.37

tot_nonchurned = tot_customers - total_churned

In [233]:
#---------------------------------------
# CHURN PERCENTAGE BY GENDER
#---------------------------------------
gender_churn = df.groupby('Gender')['Exited'].agg(
    total_customers='count',
    churned_customers='sum',
    churn_rate='mean'
)

gender_churn['churn_rate'] = (
    gender_churn['churn_rate'] * 100
).round(2)

gender_churn

        total_customers  churned_customers  churn_rate
Gender
Female             4543               1139       25.07
Male               5457                898       16.46

In [234]:
#---------------------------------------
# CHURN PERCENTAGE BY CREDIT GROUP
#---------------------------------------
creditGroup = df.groupby('CreditGroup')['Exited'].agg(
    total_customers='count',
    churned_customers='sum',
    churn_rate='mean'
)

creditGroup['churn_rate'] = (
    creditGroup['churn_rate'] * 100
).round(2)

creditGroup

/tmp/ipykernel_6255/2405738291.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  creditGroup = df.groupby('CreditGroup')['Exited'].agg(

             total_customers  churned_customers  churn_rate
CreditGroup
Poor                    2362                520       22.02
Fair                    3331                685       20.56
Good                    2428                452       18.62
Very Good               1879                380       20.22

In [235]:
#---------------------------------------
# CHURN PERCENTAGE BY AGE GROUP
#---------------------------------------
agegroup = df.groupby('AgeGroup')['Exited'].agg(
    total_customers = 'count',
    churned_customers = 'sum',
    churn_rate = 'mean'
)

agegroup['churn_rate'] = (
    agegroup['churn_rate'] * 100
).round(2)

agegroup

/tmp/ipykernel_6255/502337979.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  agegroup = df.groupby('AgeGroup')['Exited'].agg(

                 total_customers  churned_customers  churn_rate
AgeGroup
Young Adult                 1641                124        7.56
Adult                       4346                473       10.88
Middle Age                  2618                806       30.79
Late Middle Age              869                487       56.04
Senior                       526                147       27.95

In [236]:
#---------------------------------------
# CHURN PERCENTAGE BY TENURE GROUP
#---------------------------------------
tenuregroup = df.groupby('TenureGroup')['Exited'].agg(
    total_customers = 'count',
    churned_customers = 'sum',
    churn_rate = 'mean'
)

tenuregroup['churn_rate'] = (
    tenuregroup['churn_rate'] * 100
).round(2)

tenuregroup

/tmp/ipykernel_6255/1013244793.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tenuregroup = df.groupby('TenureGroup')['Exited'].agg(

                      total_customers  churned_customers  churn_rate
TenureGroup
New Customer                     2083                433       20.79
Short Term Customer              3010                625       20.76
Established Customer             3020                570       18.87
Long Term Customer               1474                314       21.30

In [237]:
#---------------------------------------
# CHURN PERCENTAGE BY GEOGRAPHY
#---------------------------------------
geography = df.groupby('Geography')['Exited'].agg(
    total_customers = 'count',
    churned_customers = 'sum',
    churn_rate = 'mean'
)

geography['churn_rate'] = (
    geography['churn_rate'] *100
).round(2)

geography

           total_customers  churned_customers  churn_rate
Geography
France                5014                810       16.15
Germany               2509                814       32.44
Spain                 2477                413       16.67

In [238]:
#---------------------------------------
# CHURN PERCENTAGE BY PRODUCT GROUP
#---------------------------------------
productgroup = df.groupby('ProductGroup')['Exited'].agg(
    total_customers = 'count',
    churned_customers = 'sum',
    churn_rate = 'mean'
)

productgroup['churn_rate'] = (
    productgroup['churn_rate'] *100
).round(2)

productgroup

/tmp/ipykernel_6255/1207635837.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  productgroup = df.groupby('ProductGroup')['Exited'].agg(

                            total_customers  churned_customers  churn_rate
ProductGroup
Single Product Customer                5084               1409       27.71
Dual Product Customer                  4590                348        7.58
Triple Product Customer                 266                220       82.71
Quadruple Product Customer               60                 60      100.00

In [239]:
#---------------------------------------
# CHURN PERCENTAGE BY HAS CREDIT CARD
#---------------------------------------
creditcard = df.groupby('HasCrCard')['Exited'].agg(
    total_customers = 'count',
    churned_customers = 'sum',
    churn_rate = 'mean'
)

creditcard['churn_rate'] = (
    creditcard['churn_rate'] *100
).round(2)

creditcard

           total_customers  churned_customers  churn_rate
HasCrCard
0                     2945                613       20.81
1                     7055               1424       20.18

In [240]:
#-------------------------------------------------
# STATISTICAL ANALYSIS: CHI SQUARE TEST OF INDEPENDENCE
# GENDER VS CHURN
# H0: THERE ARE NO SIGNIFICANT ASSOCIATIONS BETWEEN GENDER AND CHURN
# Ha: THERE IS SIGNIFICANT ASSOCIATION BETWEEN GENDER AND CHURN
# ALPHA: 0.05
#-------------------------------------------------
import scipy.stats as stats
from scipy.stats import chi2_contingency

# Create a table of gender versus customer churn
gender_table = pd.crosstab(df['Gender'], df['Exited'])

# Run the chi-square test
chi2, gender_p_value, dof, expected = chi2_contingency(gender_table)


print("Chi-square statistic:", chi2)
print("P-value:", gender_p_value)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)
gender_table

#--------------------------------------------------
# P_VALUE < 0.05
# WE REJECT THE NULL HYPOTHESIS. THERE IS A SIGNIFICANT
# ASSOCIATION BETWEEN GENDER AND CHURN
#---------------------------------------------------

Chi-square statistic: 112.91857062096116
P-value: 2.2482100097131755e-26
Degrees of freedom: 1
Expected frequencies:
 [[3617.5909  925.4091]
 [4345.4091 1111.5909]]

Exited     0     1
Gender
Female  3404  1139
Male    4559   898

In [241]:
#-------------------------------------------------
# STATISTICAL ANALYS: CRAMER V TEST
# QUESTION: HOW STRONG IS THE ASSOCICATION BETWEEN VARIABLES?
# SCALE 0 -> 1
#
# ES ≤ 0.2	The result is weak.
# 0.2 < ES ≤ 0.6	The result is moderate.
# ES > 0.6	The result is strong.
#-------------------------------------------------

import numpy as np

def v_cramers(contingency_table, chi2):
  rows, columns = contingency_table.shape
  n = contingency_table.to_numpy().sum()

  return np.sqrt(chi2 / (n * min(rows - 1, columns - 1))).round(4)

gender_es = v_cramers(gender_table, chi2)

# ------------------------------------------------
#
#
#-------------------------------------------------

In [242]:
#-------------------------------------------------
# PRODUCT COUNT VS CHURN
# H0: THERE ARE NO SIGNIFICANT ASSOCIATIONS BETWEEN # OF PRODUCTS AND CHURN
# Ha: THERE IS SIGNIFICANT ASSOCIATION BETWEEN # OF PRODUCTS AND CHURN
# ALPHA: 0.05
#-------------------------------------------------

# Create a table of # of products versus customer churn
product_table = pd.crosstab(df['ProductGroup'], df['Exited'])

# Run the chi-square test
chi2, product_p_value, dof, expected = chi2_contingency(product_table)

print("Chi-square statistic:", chi2)
print("P-value:", product_p_value)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)
product_table

#--------------------------------------------------
# P_VALUE < 0.05
# WE REJECT THE NULL HYPOTHESIS. THERE IS A SIGNIFICANT
# ASSOCIATION BETWEEN # OF PRODUCT AND CHURN
#---------------------------------------------------

Chi-square statistic: 1503.6293615070408
P-value: 0.0
Degrees of freedom: 3
Expected frequencies:
 [[4048.3892 1035.6108]
 [3655.017   934.983 ]
 [ 211.8158   54.1842]
 [  47.778    12.222 ]]

Exited                         0     1
ProductGroup
Single Product Customer     3675  1409
Dual Product Customer       4242   348
Triple Product Customer       46   220
Quadruple Product Customer     0    60

In [243]:
#-------------------------------------------------
# STATISTICAL ANALYS: CRAMER V TEST
# QUESTION: HOW STRONG IS THE ASSOCICATION BETWEEN VARIABLES?
# SCALE 0 -> 1
#
# ES ≤ 0.2	The result is weak.
# 0.2 < ES ≤ 0.6	The result is moderate.
# ES > 0.6	The result is strong.
#-------------------------------------------------


product_es = v_cramers(product_table, chi2)
product_es

# ------------------------------------------------
#
#
#-------------------------------------------------

np.float64(0.3878)

In [244]:
#-------------------------------------------------
# AGE GROUP VS CHURN
# H0: THERE ARE NO SIGNIFICANT ASSOCIATIONS BETWEEN AGE GROUP AND CHURN
# Ha: THERE IS SIGNIFICANT ASSOCIATION BETWEEN AGE GROUP AND CHURN
# ALPHA: 0.05
#-------------------------------------------------

# Create a table of # of products versus customer churn
age_table = pd.crosstab(df['AgeGroup'], df['Exited'])

# Run the chi-square test
chi2, age_p_value, dof, expected = chi2_contingency(age_table)

print("Chi-square statistic:", chi2)
print("P-value:", age_p_value)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)
age_table

#--------------------------------------------------
# P_VALUE < 0.05
# WE REJECT THE NULL HYPOTHESIS. THERE IS A SIGNIFICANT
# ASSOCIATION BETWEEN AGE GROUP AND CHURN
#---------------------------------------------------

Chi-square statistic: 1282.6743860597269
P-value: 1.899149254465315e-276
Degrees of freedom: 4
Expected frequencies:
 [[1306.7283  334.2717]
 [3460.7198  885.2802]
 [2084.7134  533.2866]
 [ 691.9847  177.0153]
 [ 418.8538  107.1462]]

Exited              0    1
AgeGroup
Young Adult      1517  124
Adult            3873  473
Middle Age       1812  806
Late Middle Age   382  487
Senior            379  147

In [245]:
#-------------------------------------------------
# STATISTICAL ANALYS: CRAMER V TEST
# QUESTION: HOW STRONG IS THE ASSOCICATION BETWEEN VARIABLES?
# SCALE 0 -> 1
#
# ES ≤ 0.2	The result is weak.
# 0.2 < ES ≤ 0.6	The result is moderate.
# ES > 0.6	The result is strong.
#-------------------------------------------------


age_es = v_cramers(age_table, chi2)
age_es

# ------------------------------------------------
#
#
#-------------------------------------------------

np.float64(0.3581)

In [246]:
#-------------------------------------------------
# TENURE VS CHURN
# H0: THERE ARE NO SIGNIFICANT ASSOCIATIONS BETWEEN TENURE GROUP AND CHURN
# Ha: THERE IS SIGNIFICANT ASSOCIATION BETWEEN TENURE GROUP AND CHURN
# ALPHA: 0.05
#-------------------------------------------------

# Create a table of # of products versus customer churn
tenure_table = pd.crosstab(df['TenureGroup'], df['Exited'])

# Run the chi-square test
chi2, tenure_p_value, dof, expected = chi2_contingency(tenure_table)

print("Chi-square statistic:", chi2)
print("P-value:", tenure_p_value)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)
tenure_table

#--------------------------------------------------
# P_VALUE > 0.05
# WE ACCEPT THE NULL HYPOTHESIS. THERE IS not A SIGNIFICANT
# ASSOCIATION BETWEEN TENURE GROUP AND CHURN
#---------------------------------------------------

Chi-square statistic: 5.414512340545942
P-value: 0.14384207925406284
Degrees of freedom: 3
Expected frequencies:
 [[1661.05507458  421.94492542]
 [2400.27641598  609.72358402]
 [2408.25075623  611.74924377]
 [1175.41775321  298.58224679]]

Exited                   0    1
TenureGroup
New Customer          1650  433
Short Term Customer   2385  625
Established Customer  2450  570
Long Term Customer    1160  314

In [247]:
#-------------------------------------------------
# STATISTICAL ANALYS: CRAMER V TEST
# QUESTION: HOW STRONG IS THE ASSOCICATION BETWEEN VARIABLES?
# SCALE 0 -> 1
#
# ES ≤ 0.2	The result is weak.
# 0.2 < ES ≤ 0.6	The result is moderate.
# ES > 0.6	The result is strong.
#-------------------------------------------------


tenure_es = v_cramers(tenure_table, chi2)
tenure_es

# ------------------------------------------------
#
#
#-------------------------------------------------

np.float64(0.0238)

In [248]:
#-------------------------------------------------
# GEOGRAPHY VS CHURN
# H0: THERE ARE NO SIGNIFICANT ASSOCIATIONS BETWEEN GEOGRAPHY AND CHURN
# Ha: THERE IS SIGNIFICANT ASSOCIATION BETWEEN GEOGRAPHY AND CHURN
# ALPHA: 0.05
#-------------------------------------------------

# Create a table of # of products versus customer churn
geography_table = pd.crosstab(df['Geography'], df['Exited'])

# Run the chi-square test
chi2, geography_p_value, dof, expected = chi2_contingency(geography_table)

print("Chi-square statistic:", chi2)
print("P-value:", geography_p_value)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)
geography_table

#--------------------------------------------------
# P_VALUE < 0.05
# WE REJECT THE NULL HYPOTHESIS. THERE IS A SIGNIFICANT
# ASSOCIATION BETWEEN GEOGRAPHY GROUP AND CHURN
#---------------------------------------------------

Chi-square statistic: 301.25533682434536
P-value: 3.8303176053541544e-66
Degrees of freedom: 2
Expected frequencies:
 [[3992.6482 1021.3518]
 [1997.9167  511.0833]
 [1972.4351  504.5649]]

Exited        0    1
Geography
France     4204  810
Germany    1695  814
Spain      2064  413

In [249]:
#-------------------------------------------------
# STATISTICAL ANALYS: CRAMER V TEST
# QUESTION: HOW STRONG IS THE ASSOCICATION BETWEEN VARIABLES?
# SCALE 0 -> 1
#
# ES ≤ 0.2	The result is weak.
# 0.2 < ES ≤ 0.6	The result is moderate.
# ES > 0.6	The result is strong.
#-------------------------------------------------


geography_es = v_cramers(geography_table, chi2)
geography_es

# ------------------------------------------------
#
#
#-------------------------------------------------

np.float64(0.1736)

In [250]:
#-------------------------------------------------
# AGE CREDIT GROUP VS CHURN
# H0: THERE ARE NO SIGNIFICANT ASSOCIATIONS BETWEEN CREDIT GROUP AND CHURN
# Ha: THERE IS SIGNIFICANT ASSOCIATION BETWEEN CREDIT GROUP AND CHURN
# ALPHA: 0.05
#-------------------------------------------------

# Create a table of # of products versus customer churn
credit_table = pd.crosstab(df['CreditGroup'], df['Exited'])

# Run the chi-square test
chi2, credit_p_value, dof, expected = chi2_contingency(credit_table)

print("Chi-square statistic:", chi2)
print("P-value:", credit_p_value)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)
credit_table

#--------------------------------------------------
# P_VALUE < 0.05
# WE REJECT THE NULL HYPOTHESIS. THERE IS A SIGNIFICANT
# ASSOCIATION BETWEEN CREDIT GROUP AND CHURN
#---------------------------------------------------

Chi-square statistic: 8.648396007382205
P-value: 0.03435002368974504
Degrees of freedom: 3
Expected frequencies:
 [[1880.8606  481.1394]
 [2652.4753  678.5247]
 [1933.4164  494.5836]
 [1496.2477  382.7523]]

Exited          0    1
CreditGroup
Poor         1842  520
Fair         2646  685
Good         1976  452
Very Good    1499  380

In [251]:
#-------------------------------------------------
# STATISTICAL ANALYS: CRAMER V TEST
# QUESTION: HOW STRONG IS THE ASSOCICATION BETWEEN VARIABLES?
# SCALE 0 -> 1
#
# ES ≤ 0.2	The result is weak.
# 0.2 < ES ≤ 0.6	The result is moderate.
# ES > 0.6	The result is strong.
#-------------------------------------------------


credit_es = v_cramers(credit_table, chi2)
credit_es

# ------------------------------------------------
#
#
#-------------------------------------------------

np.float64(0.0294)

In [252]:
p_values = [
    ['Gender', gender_p_value],
    ['ProductGroup', product_p_value],
    ['AgeGroup', age_p_value],
    ['TenureGroup', tenure_p_value],
    ['Geography', geography_p_value],
    ['CreditGroup', credit_p_value]
]

p_values = pd.DataFrame(p_values, columns=['Variable', 'P-value'])
p_values['Significant'] = p_values['P-value'] < 0.05
p_values['ES'] = [gender_es, product_es, age_es, tenure_es, geography_es, credit_es]
p_values['Association'] = p_values['ES'].apply(lambda x: 'Weak' if x <= 0.2 else ('Moderate' if 0.2 < x <= 0.6 else 'Strong'))
p_values

       Variable        P-value  Significant      ES Association
0        Gender   2.248210e-26         True  0.1063        Weak
1  ProductGroup   0.000000e+00         True  0.3878    Moderate
2      AgeGroup  1.899149e-276         True  0.3581    Moderate
3   TenureGroup   1.438421e-01        False  0.0238        Weak
4     Geography   3.830318e-66         True  0.1736        Weak
5   CreditGroup   3.435002e-02         True  0.0294        Weak